-- MySQL Workbench Synchronization
-- Generated: 2017-02-13 16:35
-- Model: New Model
-- Version: 1.0
-- Project: RealEstateMySQL
-- Author: Chris

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

ALTER TABLE `mls`.`CITY` 
DROP FOREIGN KEY `COUNTY_FK`;

ALTER TABLE `mls`.`ZIPCODE` 
DROP FOREIGN KEY `CITY_FK`;

ALTER TABLE `mls`.`COUNTY` 
CHANGE COLUMN `NAME` `NAME` VARCHAR(20) NOT NULL ,
ADD UNIQUE INDEX `NAME_UNIQUE` (`NAME` ASC);

ALTER TABLE `mls`.`CITY` 
CHANGE COLUMN `NAME` `NAME` VARCHAR(30) NOT NULL ,
CHANGE COLUMN `COUNTY_ID` `COUNTY_ID` INT(11) NOT NULL ,
ADD UNIQUE INDEX `NAME_UNIQUE` (`NAME` ASC);

ALTER TABLE `mls`.`ZIPCODE` 
CHANGE COLUMN `ZIPCODE` `ZIPCODE` INT(5) NOT NULL ,
CHANGE COLUMN `CITY_ID` `CITY_ID` INT(11) NOT NULL ,
ADD UNIQUE INDEX `ZIPCODE_UNIQUE` (`ZIPCODE` ASC);

ALTER TABLE `mls`.`CITY` 
ADD CONSTRAINT `COUNTY_FK`
  FOREIGN KEY (`COUNTY_ID`)
  REFERENCES `mls`.`COUNTY` (`COUNTY_ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `mls`.`ZIPCODE` 
ADD CONSTRAINT `CITY_FK`
  FOREIGN KEY (`CITY_ID`)
  REFERENCES `mls`.`CITY` (`CITY_ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
