-- MySQL Workbench Synchronization
-- Generated: 2017-02-14 09:05
-- Model: New Model
-- Version: 1.0
-- Project: RealEstateMySQL
-- Author: Chris

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE TABLE IF NOT EXISTS `mls`.`PROPERTY_STG` (
  `MLS_ID` VARCHAR(11) NOT NULL,
  `ZIPCODE` VARCHAR(5) NULL DEFAULT NULL,
  `CITY` VARCHAR(30) NULL DEFAULT NULL,
  `BEDS` INT(2) NULL DEFAULT NULL,
  `BATHS` INT(2) NULL DEFAULT NULL,
  `STRUCT_SQFT` DECIMAL(6,2) NULL DEFAULT NULL,
  `LOT_SQFT` DECIMAL(6,2) NULL DEFAULT NULL,
  `YEAR_BUILT` YEAR NULL DEFAULT NULL,
  `LIST_PRICE` DECIMAL(8,2) NULL DEFAULT NULL,
  `LIST_STATUS` VARCHAR(10) NULL DEFAULT NULL,
  `URL` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`MLS_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
