-- MySQL Workbench Synchronization
-- Generated: 2017-02-14 08:01
-- Model: New Model
-- Version: 1.0
-- Project: RealEstateMySQL
-- Author: Chris

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

ALTER TABLE `mls`.`ZIPCODE` 
DROP COLUMN `ZIP_ID`,
DROP PRIMARY KEY,
ADD PRIMARY KEY (`ZIPCODE`),
DROP INDEX `ZIPCODE_UNIQUE` ;

ALTER TABLE `mls`.`ZIPCODE` 
CHANGE COLUMN `ZIPCODE` `ZIPCODE` VARCHAR(5) NOT NULL ;

ALTER TABLE `mls`.`ZIPCODE` 
DROP PRIMARY KEY,
ADD PRIMARY KEY (`ZIPCODE`, `CITY_ID`);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
