-- MySQL Workbench Synchronization
-- Generated: 2017-02-13 12:52
-- Model: New Model
-- Version: 1.0
-- Project:  RealEstateMySQL
-- Author: Chris

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE TABLE IF NOT EXISTS `mls`.`COUNTY` (
  `COUNTY_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`COUNTY_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `mls`.`CITY` (
  `CITY_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(20) NULL DEFAULT NULL,
  `COUNTY_ID` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`CITY_ID`),
  INDEX `COUNTY_FK_idx` (`COUNTY_ID` ASC),
  CONSTRAINT `COUNTY_FK`
    FOREIGN KEY (`COUNTY_ID`)
    REFERENCES `mls`.`COUNTY` (`COUNTY_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `mls`.`ZIPCODE` (
  `ZIP_ID` INT(11) NOT NULL,
  `ZIPCODE` INT(5) NULL DEFAULT NULL,
  `CITY_ID` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`ZIP_ID`),
  INDEX `CITY_FK_idx` (`CITY_ID` ASC),
  CONSTRAINT `CITY_FK`
    FOREIGN KEY (`CITY_ID`)
    REFERENCES `mls`.`CITY` (`CITY_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
