-- MySQL Workbench Synchronization
-- Generated: 2017-02-15 14:10
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: Chris

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

ALTER TABLE `mls`.`PROPERTY_FACT` 
DROP FOREIGN KEY `STATUS_FK`,
DROP FOREIGN KEY `SIZE_FK`,
DROP FOREIGN KEY `ROOM_FK`,
DROP FOREIGN KEY `PRICE_FK`,
DROP FOREIGN KEY `MISC_FK`,
DROP FOREIGN KEY `ADDR_FK`;

ALTER TABLE `mls`.`PROPERTY_FACT` 
DROP COLUMN `MISC_SK`,
DROP COLUMN `SIZE_SK`,
DROP COLUMN `ROOM_SK`,
DROP COLUMN `ADDR_SK`,
CHANGE COLUMN `PROP_ID` `MLS_ID` VARCHAR(14) NOT NULL ,
CHANGE COLUMN `STATUS_SK` `STATUS_SK` INT(10) UNSIGNED NOT NULL ,
DROP INDEX `MISC_SK_UNIQUE` ,
DROP INDEX `SIZE_SK_UNIQUE` ,
DROP INDEX `ROOM_SK_UNIQUE` ,
DROP INDEX `ADDR_SK_UNIQUE` ;

ALTER TABLE `mls`.`ADDR_DIM` 
CHANGE COLUMN `ADDR_SK` `MLS_ID` VARCHAR(14) NOT NULL ;

ALTER TABLE `mls`.`ROOM_DIM` 
CHANGE COLUMN `ROOM_SK` `MLS_ID` VARCHAR(14) NOT NULL ;

ALTER TABLE `mls`.`SIZE_DIM` 
CHANGE COLUMN `SIZE_SK` `MLS_ID` VARCHAR(14) NOT NULL ,
CHANGE COLUMN `STRUCT_SQFT` `STRUCT_SQFT` DECIMAL(8,2) NULL DEFAULT NULL ,
DROP PRIMARY KEY,
ADD PRIMARY KEY (`MLS_ID`);

ALTER TABLE `mls`.`PRICE_DIM` 
ADD INDEX `FACT_FK_idx` (`MLS_ID` ASC);

ALTER TABLE `mls`.`STATUS_DIM` 
DROP COLUMN `INACT_DATE`,
CHANGE COLUMN `ACTIVE_DATE` `STATUS` VARCHAR(5) NOT NULL ,
CHANGE COLUMN `CONT_DATE` `EVENT_DATE` DATE NOT NULL ,
ADD COLUMN `MLS_ID` VARCHAR(14) NOT NULL AFTER `STATUS_SK`,
ADD INDEX `FACT_FK_idx` (`MLS_ID` ASC);

ALTER TABLE `mls`.`MISC_DIM` 
CHANGE COLUMN `MISC_SK` `MLS_ID` VARCHAR(14) NOT NULL ;

ALTER TABLE `mls`.`ADDR_DIM` 
ADD CONSTRAINT `FACT_FK`
  FOREIGN KEY (`MLS_ID`)
  REFERENCES `mls`.`PROPERTY_FACT` (`MLS_ID`)
  ON DELETE CASCADE
  ON UPDATE NO ACTION;

ALTER TABLE `mls`.`ROOM_DIM` 
ADD CONSTRAINT `FACT_FK`
  FOREIGN KEY (`MLS_ID`)
  REFERENCES `mls`.`PROPERTY_FACT` (`MLS_ID`)
  ON DELETE CASCADE
  ON UPDATE NO ACTION;

ALTER TABLE `mls`.`SIZE_DIM` 
ADD CONSTRAINT `FACT_FK`
  FOREIGN KEY (`MLS_ID`)
  REFERENCES `mls`.`PROPERTY_FACT` (`MLS_ID`)
  ON DELETE CASCADE
  ON UPDATE NO ACTION;

ALTER TABLE `mls`.`PRICE_DIM` 
ADD CONSTRAINT `FACT_FK`
  FOREIGN KEY (`MLS_ID`)
  REFERENCES `mls`.`PROPERTY_FACT` (`MLS_ID`)
  ON DELETE CASCADE
  ON UPDATE NO ACTION;

ALTER TABLE `mls`.`STATUS_DIM` 
ADD CONSTRAINT `FACT_FK`
  FOREIGN KEY (`MLS_ID`)
  REFERENCES `mls`.`PROPERTY_FACT` (`MLS_ID`)
  ON DELETE CASCADE
  ON UPDATE NO ACTION;

ALTER TABLE `mls`.`MISC_DIM` 
ADD CONSTRAINT `FACT_FK`
  FOREIGN KEY (`MLS_ID`)
  REFERENCES `mls`.`PROPERTY_FACT` (`MLS_ID`)
  ON DELETE CASCADE
  ON UPDATE NO ACTION;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
