-- MySQL Workbench Synchronization
-- Generated: 2017-02-15 11:31
-- Model: New Model
-- Version: 1.0
-- Project: RealEstateMySQL
-- Author: Chris

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE TABLE IF NOT EXISTS `mls`.`PROPERTY_FACT` (
  `PROP_ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ADDR_SK` INT(10) UNSIGNED NOT NULL,
  `ROOM_SK` INT(10) UNSIGNED NULL DEFAULT NULL,
  `SIZE_SK` INT(10) UNSIGNED NULL DEFAULT NULL,
  `PRICE_SK` INT(10) UNSIGNED NOT NULL,
  `STATUS_SK` INT(10) UNSIGNED NULL DEFAULT NULL,
  `MISC_SK` INT(10) UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`PROP_ID`),
  UNIQUE INDEX `ROOM_SK_UNIQUE` (`ROOM_SK` ASC),
  UNIQUE INDEX `SIZE_SK_UNIQUE` (`SIZE_SK` ASC),
  UNIQUE INDEX `PRICE_SK_UNIQUE` (`PRICE_SK` ASC),
  UNIQUE INDEX `STATUS_SK_UNIQUE` (`STATUS_SK` ASC),
  UNIQUE INDEX `MISC_SK_UNIQUE` (`MISC_SK` ASC),
  UNIQUE INDEX `ADDR_SK_UNIQUE` (`ADDR_SK` ASC),
  CONSTRAINT `ADDR_FK`
    FOREIGN KEY (`ADDR_SK`)
    REFERENCES `mls`.`ADDR_DIM` (`ADDR_SK`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ROOM_FK`
    FOREIGN KEY (`ROOM_SK`)
    REFERENCES `mls`.`ROOM_DIM` (`ROOM_SK`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `SIZE_FK`
    FOREIGN KEY (`SIZE_SK`)
    REFERENCES `mls`.`SIZE_DIM` (`SIZE_SK`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `PRICE_FK`
    FOREIGN KEY (`PRICE_SK`)
    REFERENCES `mls`.`PRICE_DIM` (`PRICE_SK`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `STATUS_FK`
    FOREIGN KEY (`STATUS_SK`)
    REFERENCES `mls`.`STATUS_DIM` (`STATUS_SK`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `MISC_FK`
    FOREIGN KEY (`MISC_SK`)
    REFERENCES `mls`.`MISC_DIM` (`MISC_SK`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `mls`.`ADDR_DIM` (
  `ADDR_SK` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `AREA_ID` INT(3) NOT NULL,
  `ADDR` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`ADDR_SK`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `mls`.`ROOM_DIM` (
  `ROOM_SK` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `BEDS` INT(2) NULL DEFAULT NULL,
  `FULL_BATHS` INT(2) NULL DEFAULT NULL,
  `PART_BASHS` INT(2) NULL DEFAULT NULL,
  PRIMARY KEY (`ROOM_SK`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `mls`.`SIZE_DIM` (
  `SIZE_SK` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `STRUCT_SQFT` DECIMAL(8,2) NOT NULL,
  `LOT_SIZE` DECIMAL(8,2) NULL DEFAULT NULL,
  `LOT_SIZE_UNIT` VARCHAR(5) NULL DEFAULT NULL,
  PRIMARY KEY (`SIZE_SK`, `STRUCT_SQFT`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `mls`.`PRICE_DIM` (
  `PRICE_SK` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `MLS_ID` VARCHAR(14) NOT NULL,
  `LIST_PRICE` DECIMAL(10,2) NOT NULL,
  `LIST_DATE` DATE NOT NULL,
  PRIMARY KEY (`PRICE_SK`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `mls`.`STATUS_DIM` (
  `STATUS_SK` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ACTIVE_DATE` DATE NOT NULL,
  `CONT_DATE` DATE NULL DEFAULT NULL,
  `INACT_DATE` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`STATUS_SK`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `mls`.`MISC_DIM` (
  `MISC_SK` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `YEAR_BUILT` VARCHAR(10) NULL DEFAULT NULL,
  `URL` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`MISC_SK`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
