ALTER TABLE `mls`.`CITY` 
CHANGE COLUMN `NAME` `NAME` VARCHAR(20) NOT NULL ;

ALTER TABLE `mls`.`PROPERTY_STG` 
CHANGE COLUMN `CITY` `CITY` VARCHAR(20) NULL DEFAULT NULL ,
ADD COLUMN `ADDR` VARCHAR(50) NULL DEFAULT NULL AFTER `CITY`;

ALTER TABLE `mls`.`PROPERTY_STG` 
CHANGE COLUMN `BATHS` `FULL_BATHS` INT(2) NULL DEFAULT NULL ,
ADD COLUMN `PART_BATHS` INT(2) NULL DEFAULT NULL AFTER `FULL_BATHS`;

ALTER TABLE `mls`.`PROPERTY_STG` 
CHANGE COLUMN `LOT_SQFT` `LOT_SIZE` DECIMAL(6,2) NULL DEFAULT NULL ,
ADD COLUMN `LOT_SIZE_UNIT` VARCHAR(5) NULL DEFAULT NULL AFTER `LOT_SIZE`;

ALTER TABLE `mls`.`PROPERTY_STG` 
CHANGE COLUMN `STRUCT_SQFT` `STRUCT_SQFT` DECIMAL(8,2) NULL DEFAULT NULL ,
CHANGE COLUMN `LOT_SIZE` `LOT_SIZE` DECIMAL(8,2) NULL DEFAULT NULL ,

ALTER TABLE `mls`.`ZIPCODE` 
ADD COLUMN `AREA_ID` VARCHAR(45) NOT NULL FIRST,
DROP PRIMARY KEY,
ADD PRIMARY KEY (`AREA_ID`),
ADD UNIQUE INDEX `AREA_UNIQUE` (`ZIPCODE` ASC, `CITY_ID` ASC);

ALTER TABLE `mls`.`ZIPCODE` 
CHANGE COLUMN `AREA_ID` `AREA_ID` INT(11) NOT NULL AUTO_INCREMENT ;

ALTER TABLE `mls`.`PROPERTY_STG` 
CHANGE COLUMN `LOT_SIZE` `LOT_SIZE` DECIMAL(10,2) NULL DEFAULT NULL ;


ALTER TABLE `mls`.`PROPERTY_STG` 
CHANGE COLUMN `MLS_ID` `MLS_ID` VARCHAR(14) NOT NULL ,
CHANGE COLUMN `LOT_SIZE` `LOT_SIZE` DECIMAL(8,2) NULL DEFAULT NULL ,
CHANGE COLUMN `YEAR_BUILT` `YEAR_BUILT` INT(4) NULL DEFAULT NULL ;