SELECT * FROM PROPERTY_STG;

INSERT INTO PROPERTY_STG (MLS_ID,  
LOT_SIZE_UNIT, YEAR_BUILT)
VALUES ('MLS122341', null, 1989);

SELECT LIST_PRICE / STRUCT_SQFT, MLS_ID FROM PROPERTY_STG
ORDER BY 1; 

SELECT * FROM PROPERTY_STG WHERE MLS_ID = 'ML81636165';
SELECT * FROM ZIPCODE
DESC ZIPCODE

SELECT * FROM PROPERTY_STG ORDER BY MLS_ID DESC
