SELECT * FROM COUNTY ;

INSERT INTO COUNTY (NAME) VALUES ('Santa Clara');
delete from COUNTY WHERE COUNTY_ID >= 1;

ALTER TABLE COUNTY AUTO_INCREMENT = 1;


SELECT COUNTY_ID FROM COUNTY WHERE LOWER(NAME) like '%santa clara%'